// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEOSTHSwAfl9aItKbvpG-MbT9hG98M-UU',
    appId: '1:983491486762:android:6cb3de5b4e906e0aa98f53',
    messagingSenderId: '983491486762',
    projectId: 'dropcity-aadac',
    storageBucket: 'dropcity-aadac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk-SlFOL1JWORMnRDCruj29xSFwjbfuiQ',
    appId: '1:983491486762:ios:c79783fb202ac796a98f53',
    messagingSenderId: '983491486762',
    projectId: 'dropcity-aadac',
    storageBucket: 'dropcity-aadac.firebasestorage.app',
    iosBundleId: 'com.example.citydrop',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNRnMbq_krhO03iRIY-JXJ30lpCdKou4w',
    appId: '1:983491486762:web:dbf47c3d44555e68a98f53',
    messagingSenderId: '983491486762',
    projectId: 'dropcity-aadac',
    authDomain: 'dropcity-aadac.firebaseapp.com',
    storageBucket: 'dropcity-aadac.firebasestorage.app',
    measurementId: 'G-L5G5SGWRVZ',
  );

}